version: '3.1'

services: 
    teamcity:
        restart: unless-stopped
        image: jetbrains/teamcity-server:2017.1.2
        ports: 
            - "0.0.0.0:8111:8111"
        volumes: 
            - "/mnt/teamcity:/mnt/teamcity"
        
    teamcity-agent:
        restart: unless-stopped
        image: jetbrains/teamcity-agent:2017.1.2
        environment: 
            SERVER_URL: http://teamcity:8111
        volumes: 
            - /var/run/docker.sock:/var/run/docker.sock