version: '3.1'

services:
  generator:
    image: my-registry:55000/dockeraspnetcore:ci-${DOCKERASPNETCORE_BUILD_NUMBER-10}
    #orts:
    #  - "8080:80"
  mail:
    image: mailhog/mailhog
    #ports:
    #  - "8025:8025"
  integration:
    image: my-registry:55000/dockeraspnetcore:integration-${BUILD_NUMBER-10}
    build: .
    environment:
      - TEAMCITY_PROJECT_NAME