version: '3.1'

services:
  generator:
    build:
      context: .
    image: my-registry:55000/dockeraspnetcore:ci-8
    ports:
      - "8080:80"
  mailpipeline:
    image: mailhog/mailhog
    ports:
      - "8025:8025"