version: '3.1'

services:
  generator:
    build:
      context: .
    image: prasanim/aspnetcoregeneratorpipeline:multi
    ports:
      - "8080:80"
  mailpipeline:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"